In [10]:
import numpy as np
import pandas as pd
from keras.utils import np_utils
from keras.models import Sequential
from keras.layers import Dense, Activation, Input, Dropout
from sklearn.preprocessing import LabelEncoder
from sklearn.model_selection import train_test_split

In [49]:
data = pd.read_csv('../bank-additional/bank-additional.csv',sep=';')
data.head()

,age,job,marital,education,default,housing,loan,contact,month,day_of_week,...,campaign,pdays,previous,poutcome,emp.var.rate,cons.price.idx,cons.conf.idx,euribor3m,nr.employed,y
0,30,blue-collar,married,basic.9y,no,yes,no,cellular,may,fri,...,2,999,0,nonexistent,-1.8,92.893,-46.2,1.313,5099.1,no
1,39,services,single,high.school,no,no,no,telephone,may,fri,...,4,999,0,nonexistent,1.1,93.994,-36.4,4.855,5191.0,no
2,25,services,married,high.school,no,yes,no,telephone,jun,wed,...,1,999,0,nonexistent,1.4,94.465,-41.8,4.962,5228.1,no
3,38,services,married,basic.9y,no,unknown,unknown,telephone,jun,fri,...,3,999,0,nonexistent,1.4,94.465,-41.8,4.959,5228.1,no
4,47,admin.,married,university.degree,no,yes,no,cellular,nov,mon,...,1,999,0,nonexistent,-0.1,93.200,-42.0,4.191,5195.8,no

In [50]:
categorical_columns = ['job','marital','education','default','housing','loan','contact','month','day_of_week','poutcome','y']

In [51]:
le = LabelEncoder()
for ix in categorical_columns:
    data[ix] = le.fit_transform(data[ix])

In [52]:
data = data.values

In [53]:
data_x = data[:,:-1]
data_y = data[:,-1]

In [54]:
x_train, x_test, y_train, y_test = train_test_split(data_x, data_y, test_size=0.2)

In [60]:
model = Sequential()

In [69]:
model.add( Dense( 64, input_shape = (20,) ) )
model.add( Activation('relu') )
model.add( Dropout(0.2) )
model.add( Dense( 128 ) )
model.add( Activation('relu') )
model.add( Dropout(0.2) )
model.add( Dense( 64 ) )
model.add( Activation('relu') )
model.add( Dropout(0.2) )
model.add( Dense( 1 ) )
model.add( Activation('sigmoid') )

In [66]:
model.summary()

_________________________________________________________________
Layer (type)                 Output Shape              Param #
=================================================================
dense_36 (Dense)             (None, 64)                1344
_________________________________________________________________
activation_36 (Activation)   (None, 64)                0
_________________________________________________________________
dropout_22 (Dropout)         (None, 64)                0
_________________________________________________________________
dense_37 (Dense)             (None, 128)               8320
_________________________________________________________________
activation_37 (Activation)   (None, 128)               0
_________________________________________________________________
dropout_23 (Dropout)         (None, 128)               0
_________________________________________________________________
dense_38 (Dense)             (None, 64)                8256
_________________________________________________________________
activation_38 (Activation)   (None, 64)                0
_________________________________________________________________
dense_39 (Dense)             (None, 1)                 65
_________________________________________________________________
activation_39 (Activation)   (None, 1)                 0
_________________________________________________________________
dense_40 (Dense)             (None, 64)                128
_________________________________________________________________
activation_40 (Activation)   (None, 64)                0
_________________________________________________________________
dense_41 (Dense)             (None, 128)               8320
_________________________________________________________________
activation_41 (Activation)   (None, 128)               0
_________________________________________________________________
dense_42 (Dense)             (None, 64)                8256
_________________________________________________________________
activation_42 (Activation)   (None, 64)                0
_________________________________________________________________
dense_43 (Dense)             (None, 1)                 65
_________________________________________________________________
activation_43 (Activation)   (None, 1)                 0
=================================================================
Total params: 17,985
Trainable params: 17,985
Non-trainable params: 0
_________________________________________________________________

In [67]:
model.compile( optimizer='adam', loss = 'binary_crossentropy', metrics=['accuracy'] )

In [68]:
model.fit(x_train, y_train,epochs=20,validation_data=(x_test,y_test))

Train on 3295 samples, validate on 824 samples
Epoch 1/20
3295/3295 [==============================] - 2s 464us/step - loss: 0.6738 - acc: 0.8926 - val_loss: 0.6556 - val_acc: 0.8823
Epoch 2/20
3295/3295 [==============================] - 0s 127us/step - loss: 0.6372 - acc: 0.8926 - val_loss: 0.6221 - val_acc: 0.8823
Epoch 3/20
3295/3295 [==============================] - 0s 121us/step - loss: 0.6042 - acc: 0.8926 - val_loss: 0.5916 - val_acc: 0.8823
Epoch 4/20
3295/3295 [==============================] - 0s 121us/step - loss: 0.5746 - acc: 0.8926 - val_loss: 0.5646 - val_acc: 0.8823
Epoch 5/20
3295/3295 [==============================] - 0s 116us/step - loss: 0.5481 - acc: 0.8926 - val_loss: 0.5403 - val_acc: 0.8823
Epoch 6/20
3295/3295 [==============================] - 0s 118us/step - loss: 0.5241 - acc: 0.8926 - val_loss: 0.5188 - val_acc: 0.8823
Epoch 7/20
3295/3295 [==============================] - 1s 156us/step - loss: 0.5028 - acc: 0.8926 - val_loss: 0.4994 - val_acc: 0.8823
Epoch 8/20
3295/3295 [==============================] - 0s 131us/step - loss: 0.4837 - acc: 0.8926 - val_loss: 0.4822 - val_acc: 0.8823
Epoch 9/20
3295/3295 [==============================] - 0s 120us/step - loss: 0.4668 - acc: 0.8926 - val_loss: 0.4670 - val_acc: 0.8823
Epoch 10/20
3295/3295 [==============================] - 0s 127us/step - loss: 0.4516 - acc: 0.8926 - val_loss: 0.4534 - val_acc: 0.8823
Epoch 11/20
3295/3295 [==============================] - 0s 124us/step - loss: 0.4381 - acc: 0.8926 - val_loss: 0.4414 - val_acc: 0.8823
Epoch 12/20
3295/3295 [==============================] - 0s 133us/step - loss: 0.4262 - acc: 0.8926 - val_loss: 0.4309 - val_acc: 0.8823
Epoch 13/20
3295/3295 [==============================] - 0s 139us/step - loss: 0.4156 - acc: 0.8926 - val_loss: 0.4215 - val_acc: 0.8823
Epoch 14/20
3295/3295 [==============================] - 0s 131us/step - loss: 0.4061 - acc: 0.8926 - val_loss: 0.4134 - val_acc: 0.8823
Epoch 15/20
3295/3295 [==============================] - 0s 115us/step - loss: 0.3978 - acc: 0.8926 - val_loss: 0.4061 - val_acc: 0.8823
Epoch 16/20
3295/3295 [==============================] - 0s 125us/step - loss: 0.3904 - acc: 0.8926 - val_loss: 0.3997 - val_acc: 0.8823
Epoch 17/20
3295/3295 [==============================] - 0s 145us/step - loss: 0.3839 - acc: 0.8926 - val_loss: 0.3941 - val_acc: 0.8823
Epoch 18/20
3295/3295 [==============================] - 0s 123us/step - loss: 0.3781 - acc: 0.8926 - val_loss: 0.3893 - val_acc: 0.8823
Epoch 19/20
3295/3295 [==============================] - 0s 130us/step - loss: 0.3731 - acc: 0.8926 - val_loss: 0.3852 - val_acc: 0.8823
Epoch 20/20
3295/3295 [==============================] - 0s 117us/step - loss: 0.3686 - acc: 0.8926 - val_loss: 0.3815 - val_acc: 0.8823